@echo off
@echo Loading cash data (df usd)...
REM echo loading cash dp data ...
cd "c:\Program Files\Pentaho\data-integration"
pan.bat /file:c:\RealWarehouse\fact\populate_cashdrawer_df_usd.ktr /level:Basic >> C:\RealWarehouse\logs\trans.log

